export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const DATA_ERROR = 'DATA_ERROR';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const DELETE_DATA_SUCCESS ='DELETE_DATA_SUCCESS'
export const CREATE_SUCCESS ='CREATE_SUCCESS'
export const DATA_SUCCESS ='DATA_SUCCESS'
export const DELETTA_SUCCES ='DELETTA_SUCCES'